### ISSUE TITLE
Paginación: habilitar opción para navegar a la primera y última página

### ISSUE THREAD

**Issue by jhonatantirado** [rfernandezv/inkafarma-web#1]
Actualmente, solo se puede avanzar o retroceder la página de 1 en 1
Se requiere la opción para navegar a la primera o a la última página con un solo clic

**Comment by rfernandezv** [comment]
También se puede implementar de navegar hacia una determinada página.

**Comment by rfernandezv** [comment]
Se implementó lo solicitado.
