### ISSUE TITLE
Búsqueda: buscar en todas las páginas, no solo en la página actual

### ISSUE THREAD

**Issue by jhonatantirado** [rfernandezv/inkafarma-web#2]
Actualmente, al buscar, solo busca en el cliente, en la página actual.
Debe buscar en todas las páginas, en el servidor

**Comment by rfernandezv** [comment]
Eso haría que en cada tecla presionada consulte al servidor. No afectaría el rendimiento?. En todo caso haríamos otra opción de búsquedas específicas.

**Comment by rfernandezv** [comment]
Listo, implementado
